//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateDocument.Soat.Messages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GenerateDocument.Soat.Messages.ContentMessages", typeof(ContentMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PolicyNumberField {
            get {
                return ResourceManager.GetString("PolicyNumberField", resourceCulture);
            }
        }
        
        internal static string FromInitialField {
            get {
                return ResourceManager.GetString("FromInitialField", resourceCulture);
            }
        }
        
        internal static string ToInitialField {
            get {
                return ResourceManager.GetString("ToInitialField", resourceCulture);
            }
        }
        
        internal static string FromFinalField {
            get {
                return ResourceManager.GetString("FromFinalField", resourceCulture);
            }
        }
        
        internal static string ToFinalField {
            get {
                return ResourceManager.GetString("ToFinalField", resourceCulture);
            }
        }
        
        internal static string PlateField {
            get {
                return ResourceManager.GetString("PlateField", resourceCulture);
            }
        }
        
        internal static string CategoryField {
            get {
                return ResourceManager.GetString("CategoryField", resourceCulture);
            }
        }
        
        internal static string UseField {
            get {
                return ResourceManager.GetString("UseField", resourceCulture);
            }
        }
        
        internal static string SeriesField {
            get {
                return ResourceManager.GetString("SeriesField", resourceCulture);
            }
        }
        
        internal static string FullNameField {
            get {
                return ResourceManager.GetString("FullNameField", resourceCulture);
            }
        }
        
        internal static string PremiumField {
            get {
                return ResourceManager.GetString("PremiumField", resourceCulture);
            }
        }
        
        internal static string DateOfIssueField {
            get {
                return ResourceManager.GetString("DateOfIssueField", resourceCulture);
            }
        }
        
        internal static string TimeOfIssueField {
            get {
                return ResourceManager.GetString("TimeOfIssueField", resourceCulture);
            }
        }
        
        internal static string SectionPolicyHolder {
            get {
                return ResourceManager.GetString("SectionPolicyHolder", resourceCulture);
            }
        }
        
        internal static string SectionPolicyDetail {
            get {
                return ResourceManager.GetString("SectionPolicyDetail", resourceCulture);
            }
        }
        
        internal static string InsuranceCompany {
            get {
                return ResourceManager.GetString("InsuranceCompany", resourceCulture);
            }
        }
        
        internal static string EmergencyCase {
            get {
                return ResourceManager.GetString("EmergencyCase", resourceCulture);
            }
        }
        
        internal static string ValidityMessage {
            get {
                return ResourceManager.GetString("ValidityMessage", resourceCulture);
            }
        }
        
        internal static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
    }
}
